LABEL EmuELEC
  LINUX /KERNEL
  FDT /rk3326-evb-lp3-v12-linux.dtb
  APPEND boot=UUID=0503-1725 disk=UUID=ebc53d1d-451d-4b72-8681-1adb08788161 quiet console=ttyFIQ0 console=tty0 net.iframes=0 fbcon=rotate:3 ssh consoleblank=0
